### ISSUE TITLE
Extension key missing in composer.json

### ISSUE THREAD

**Issue by marble** [lochmueller/autoloader#182] opened 2022-03-16 22:01 UTC
composer is telling me:
"""The TYPO3 extension package "lochmueller/autoloader", does not define an extension key in its composer.json. Please report this to the author of this package. Specifying the extension key will be mandatory in future versions of TYPO3 (see: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html#extra)"""

**Comment by lochmueller** [comment] 2022-03-17 07:23
@marble Could you post your EXT:autoloader version. The extension key is defined in the composer.json since March 2021: https://github.com/lochmueller/autoloader/blob/master/composer.json#L53 Perhaps you see the warning, because the version is older than a year?

Regrads,
Tim

**Comment by marble** [comment] 2022-03-17 07:39
Ah, sorry, you're probably right. TBH, I'm just starting with ddev and composer and I'm quite unexperienced. So I - naively - thought, "just let him know". Yes, let me see, it's probably an older version, because I'm doing a 10.4 installation with `ddev composer create "typo3/cms-base-distribution:^10.4"` and `ddev composer require lochmueller/autoloader`.  And that pulled
<pre>
$EM_CONF[$_EXTKEY] = [
    'title'            => 'Autoloader',
    'version' => '7.1.4',
    'state'            => 'stable',
    // ...
];
</pre>

So, am I doing something wrong? I'm on the way to migrate an 9.x installation to 11.

**Comment by lochmueller** [comment] 2022-03-17 07:42
Hey @marble 
Do you check `composer why-not lochmueller/autoloader:7.2.0`? Perhaps you using a old PHP version and could not install the current version? I will close this issue, because the problem is solved in the current version.
Regards,
Tim

**Closed by lochmueller** 2022-03-17 07:42 UTC

**Comment by marble** [comment] 2022-03-17 08:32
Ah, thank you. It's PHP 7.2, that's the culprit. So I'll add `ddev config  --php-version="7.4"` again. I was under the impression this was DDEV's default, but it isn't.
