### ISSUE TITLE
Example Extension

### ISSUE THREAD

**Issue by fduarte42** [lochmueller/autoloader#34] opened 2015-12-01 17:29 UTC
I tried to use the autoloader_plugin as an example, but as soon es ein changed the namespaces, it seems that typo3 cannot find the controller anymore. What am I doing wrong?

My extension can be downloaded here: https://dl.dropboxusercontent.com/u/24707107/ohmex.zip

**Comment by lochmueller** [comment] 2015-12-01 18:24
Please add same more information (TYPO3 Version, autoloader version). Are you in non-composer mode in TYPO3 > 7.x? Than you have to drop typo3temp/autoload/ if you change the class structure.

**Comment by fduarte42** [comment] 2015-12-02 09:05
I am using Typo3 7 LTS installed via composer. Autoloader is 1.11.1.
Thank you

**Comment by lochmueller** [comment] 2015-12-02 10:56
Do you try to remove the folder (typo3temp/autoload/) or run the CLI for the dumpClassLoader? The ohmex example extension seems to be right...

**Comment by fduarte42** [comment] 2015-12-02 13:10
there is no typo3temp/autoload, but I deleted the hole directory and it didn't work. How do I call the dumpClassLoader?

Here a Screenshot of the error attached.
![bildschirmfoto 2015-12-02 um 14 08 48](https://cloud.githubusercontent.com/assets/2005497/11531616/76cc1056-98fe-11e5-84c0-d36b58977946.png)

**Comment by fduarte42** [comment] 2015-12-02 13:48
I did a fresh install of typo3 with this composer.json

{
	"repositories": [
		{ "type": "composer", "url": "http://composer.typo3.org/" }
	],
	"name": "typo3/cms-base-distribution",
	"description" : "TYPO3 CMS Base Distribution",
	"license": "GPL-2.0+",
	"require": {
		"typo3/cms": "7.6.*",
		"typo3-ter/autoloader": "1.*",
		"helhum/typo3-console": "1.2.*"
	},
	"require-dev": {
		"mikey179/vfsStream": "1.4.*@dev",
		"phpunit/phpunit": "~4.7.0"
	},
	"extra": {
		"typo3/cms": {
			"cms-package-dir": "{$vendor-dir}/typo3/cms",
			"web-dir": "web"
		}
	}
}

But I still have this problem

**Comment by fduarte42** [comment] 2015-12-02 13:50
if I try to use the console after installing, I get the following error:

$ ./typo3cms help

Uncaught Exception in TYPO3 CMS Class OH\Ohmex\Controller\FirstController does not exist
thrown in file ext/autoloader/Classes/Utility/ReflectionUtility.php
in line 30

#0 Helhum\Typo3Console\Error\ExceptionHandler::handleException()

**Comment by fduarte42** [comment] 2015-12-02 15:12
Here is the typo3 Exception:
[TYPO3 Exception.pdf](https://github.com/lochmueller/autoloader/files/49848/TYPO3.Exception.pdf)

**Comment by lochmueller** [comment] 2015-12-02 15:14
I will check this in a composer env in the next days. It is a error of the Class autoloading mechanism (not the autoloader extension), because the structure of the folder, files and classnames in the dummy extension is right.

**Comment by lochmueller** [comment] 2015-12-02 18:42
Hey @fduarte42 
I install your extension and cannot reproduce the error!?! I think it is a SPL autoload problem in your instance (not related to the autoloader).
Autoloader generate the language file and the plugins are selectable in the backend:
![bildschirmfoto 2015-12-02 um 19 40 43](https://cloud.githubusercontent.com/assets/3907126/11540362/aa2f6758-992c-11e5-82df-2fc015876f17.png)

**Comment by fduarte42** [comment] 2015-12-03 14:01
I'm using php 5.5. Which version did you use? I just don't understand, why you extension is working without changing the namespaces. But as soon es I rename the extension and change the namespaces it doesn't work. Any Idea?

**Comment by lochmueller** [comment] 2015-12-03 14:34
Do you use any OPcaches (e.g. http://php.net/manual/de/book.opcache.php), that cache the classes? in my t.6 test env I also use PHP 5.5 without any problems...

**Comment by fduarte42** [comment] 2015-12-03 14:41
On typo3 6.2 LTS the extension is working without problems. I use APCu as a Cache.

**Comment by lochmueller** [comment] 2016-01-25 20:38
Hey @fduarte42 
any news for this topic? Do you invest same time in debugging?
Regards,
Tim

**Comment by lochmueller** [comment] 2016-03-02 13:18
I close this issue, because there are no news or debugging information.

**Closed by lochmueller** 2016-03-02 13:18 UTC
